#!/bin/bash
set -euxo pipefail

cat<< "EOF" 

$$$$$$$\  $$$$$$$$\ $$\      $$\ $$$$$$$\  
$$  __$$\ $$  _____|$$ | $\  $$ |$$  __$$\ 
$$ |  $$ |$$ |      $$ |$$$\ $$ |$$ |  $$ |
$$ |  $$ |$$$$$\    $$ $$ $$\$$ |$$$$$$$\ |
$$ |  $$ |$$  __|   $$$$  _$$$$ |$$  __$$\ 
$$ |  $$ |$$ |      $$$  / \$$$ |$$ |  $$ |
$$$$$$$  |$$$$$$$$\ $$  /   \$$ |$$$$$$$  |
\_______/ \________|\__/     \__|\_______/ 

This shit fire$$$$                                                                                                                                                                                                                                                                                                                                        
EOF

build(){

    mkdir -p ./files/hive
    mkdir -p ./files/spark
    mkdir -p ./files/hadoop
    mkdir -p ./files/m2
    mkdir -p $BENCH_DATA_DIR
    docker build -t spark-base:3.0.1 ./docker/base 
    docker build -t spark-master:3.0.1 ./docker/spark-master
    docker build -t spark-worker:3.0.1 ./docker/spark-worker
    docker build -t mysql:8.0.0 ./docker/mysql
}


pyspark(){
    docker-compose exec -it spark-master:3.0.1 bash -c "pyspark"
}


notebook(){
    docker-compose up
    docker-compose exec -it --remove  spark-master:3.0.1 bash -c "jupyter notebook"
}

hive(){

    docker-compose exec -it spark-master:3.0.1 bash -c "hive" >&2
}

up(){

    docker-compose up --remove-orphans
    
}


down(){

    docker-compose down
}

"$@"
