version: "3.7"
services:
  mysql:
    image: mysql:8.0.0
    hostname: mysql
    ports:
      - "3306:3306"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.7
  spark-master:
    image: spark-master:3.0.1
    container_name: spark-master
    hostname: spark-master
    depends_on:
      - mysql
    ports:
      - "8080:8080"
      - "7077:7077"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
       - ./files/app:/opt/spark/app
       - ./files/m2:/opt/spark/.m2
    environment:
      - "SPARK_HOME=/opt/spark"
      - "PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/build:$PYTHONPATH"
      - "PYTHONPATH=$SPARK_HOME/python/lib/py4j-*-src.zip:$PYTHONPATH"
      - "PYSPARK_SUBMIT_ARGS='--packages spark-streaming3.0.1,spark:kafka,3.0.1 pyspark-shell'"
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_PUBLIC_DNS=127.0.0.1"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_WORKER_PORT=6066"
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "SPARK_MASTER_WEBUI_PORT=8080"
      - "HOST=local"
  spark-worker-1:
    image: spark-worker:3.0.1
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_HOME=/opt/spark"
      - "PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/build:$PYTHONPATH"
      - "PYTHONPATH=$SPARK_HOME/python/lib/py4j-*-src.zip:$PYTHONPATH"
      - "SPARK_LOCAL_IP=spark-worker-1"
      - "SPARK_PUBLIC_DNS=127.0.0.1"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_WORKER_PORT=6066"
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "HOST=local"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.3
    volumes:
       - ./files/app:/opt/spark/app
       - ./files/m2:/opt/spark/.m2
  spark-worker-2:
    image: spark-worker:3.0.1
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8084:8084"
    environment:
      - "SPARK_HOME=/opt/spark"
      - "PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/build:$PYTHONPATH"
      - "PYTHONPATH=$SPARK_HOME/python/lib/py4j-*-src.zip:$PYTHONPATH"
      - "SPARK_LOCAL_IP=spark-worker-2"
      - "SPARK_PUBLIC_DNS=127.0.0.1"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_WORKER_PORT=6066"
      - "SPARK_WORKER_WEBUI_PORT=8084"
      - "HOST=local"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.4
    volumes:
       - ./files/app:/opt/spark/app
       - ./files/m2:/opt/spark/.m2
networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16