version: "3.7"
services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    ports:
      - "3306:3306"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.7
  spark-master:
    image: spark-master:3.0.1
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
       - ./files/spark-apps:/opt/spark-apps
       - ./files/spark-data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=10.5.0.2"
  livy:
    image: livy:0.7.0
    container_name: livy
    hostname: livy
    ports:
      - "8998:8998"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.6
    volumes:
        - ./files/spark-apps:/opt/spark-apps
        - ./files/spark-data:/opt/spark-data
    environment:
      - "SPARK_MASTER_HOST=spark-master"
      - "SPARK_MASTER_PORT=7077"
  spark-worker-1:
    image: spark-worker:3.0.1
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_MASTER_HOST=spark-master"
      - "SPARK_LOCAL_IP=10.5.0.3"
      - "HOST=localhost"
      - "SPARK_WORKER_WEBUI_PORT=8081"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.3
    volumes:
       - ./files/spark-apps:/opt/spark-apps
       - ./files/spark-data:/opt/spark-data
  jupyterlab:
    image: jupyterlab:latest
    container_name: jupyterlab
    hostname: jupyterlab
    ports:
      - "8888:8888"
    networks:
      spark-network:
        ipv4_address: 10.5.0.9
    environment:
      - "JUPYTER_ENABLE_LAB=True"
  spark-worker-2:
    image: spark-worker:3.0.1
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8084:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_MASTER_HOST=spark-master"
      - "SPARK_LOCAL_HOSTNAME=spark-worker-2"
      - "SPARK_LOCAL_IP=10.5.0.4"
      -  SPARK_PUBLIC_DNS=spark-worker-2
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "HOST=localhost"
      #https://stackoverflow.com/questions/32719007/spark-spark-public-dns-and-spark-local-ip-on-stand-alone-cluster-with-docker-con
    networks: 
      spark-network:
        ipv4_address: 10.5.0.4
    volumes:
       - ./files/spark-apps:/opt/spark-apps
       - ./files/spark-data:/opt/spark-data
  spark-worker-3:
    image: spark-worker:3.0.1
    container_name: spark-worker-3
    hostname: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8085:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_MASTER_HOST=spark-master"
      - "SPARK_LOCAL_HOSTNAME=spark-worker-3"
      - "SPARK_LOCAL_IP=10.5.0.5"
      - "SPARK_PUBLIC_DNS=spark-worker-3"
      - "SPARK_WORKER_WEBUI_PORT=8081"
      - "HOST=localhost"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.5
    volumes:
       - ./files/spark-apps:/opt/spark-apps
       - ./files/spark-data:/opt/spark-data
networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16